server:
  port: 80
  servlet:
    context-path: /vhr
    application-display-name: vhr
       
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    autoRuntimeDialect: true   